### ISSUE TITLE
Exceptions get mangled in certain circumstances

### ISSUE THREAD

**Issue by hynek** [itamarst/crochet#77] opened 2015-02-18 12:38 UTC
I’m frequently getting exceptions like this one:

```
Traceback (most recent call last):
  File "../bin/epp_query", line 9, in <module>
    load_entry_point('vrmd-txepp==3', 'console_scripts', 'epp_query')()
  File "/vrmd/domainsws/local/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/vrmd/domainsws/local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/vrmd/domainsws/local/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/vrmd/domainsws/local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/vrmd/domainsws/local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/vrmd/domainsws/local/lib/python2.7/site-packages/txepp/cli.py", line 48, in check
    results = c.domain_check(domains if domains else [TD])
  File "/vrmd/domainsws/local/lib/python2.7/site-packages/crochet/_eventloop.py", line 461, in wrapper
    return eventual_result.wait(timeout)
  File "/vrmd/domainsws/local/lib/python2.7/site-packages/crochet/_eventloop.py", line 231, in wait
    result.raiseException()
  File "<string>", line 2, in raiseException
TypeError: cert must be an X509 instance
```

Which is not helpful for debugging. :)

**Comment by itamarst** [comment] 2015-02-21 15:11
I will try to see if I can reproduce this at some point, maybe even this weekend. Can you provide a minimal reproducer? That'd speed things up.

**Comment by hynek** [comment] 2015-02-21 15:32
I had a bad conscience reporting it because nope, nothing. :-/

**Comment by itamarst** [comment] 2015-02-22 01:05
OK, pretty sure the issue is that `Deferred` calls `Failure.cleanFailure`, which wipes out the traceback object. This seems like unnecessary paranoia given modern Python can deal with circular references. Can you try this and see if it fixes the problem?

```
from twisted.python.failure import Failure
Failure.cleanFailure = lambda self: None
```

**Comment by hynek** [comment] 2015-02-22 09:38
It does indeed!

**Comment by itamarst** [comment] 2015-02-22 13:47
Ah, so memory resurfaces:
1. This *is* an issue re memory leaks; you can end up with massive memory leaks doing what I suggested above.
2. There's a documented workaround (search for `original_failure` in https://crochet.readthedocs.org/en/latest/api.html).
3. On Python 3.4 there's an API for clearing locals off the traceback, which would be a good substitute for hack above (and should probably be in Twisted proper).

**Comment by itamarst** [comment] 2015-02-22 13:49
Pre-3.4, doing the obvious thing of clearing locals on the traceback's frame has some obvious problems:

```
>>> tb.tb_frame.f_locals
{'exc': <traceback object at 0x7f8a1338bea8>, '__builtins__': <module '__builtin__' (built-in)>, '__package__': None, 'sys': <module 'sys' (built-in)>, '__name__': '__main__', 'tb': <traceback object at 0x7f8a1338bea8>, '__doc__': None}
>>> tb.tb_frame.f_locals.clear()
>>> tb.tb_frame.f_locals
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'tb' is not defined
```

**Comment by itamarst** [comment] 2015-02-23 00:47
Still can't think of a good solution for <3.4.

**Comment by itamarst** [comment] 2015-04-26 17:19
Filed upstream, with some potential ideas for older versions of Python: https://twistedmatrix.com/trac/ticket/7873#ticket

**Comment by itamarst** [comment] 2015-05-06 00:18
Going to close this and just leave it as upstream issue. The 3.4 case is an easy one, if that helps you with your immediate use case.

**Closed by itamarst** 2015-05-06 00:18 UTC
